{% set name = "six" %}
{% set version = "1.10.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "105f8d68616f8248e24bf0e9372ef04d3cc10104f1980f54d57b2ce73a5ad56a" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

about:
  home: http://pypi.python.org/pypi/six/
  license: MIT License
  license_family: MIT
  license_file: ''
  summary: Python 2 and 3 compatibility utilities
  description: 'Six is a Python 2 and 3 compatibility library.  It provides utility functions

    for smoothing over the differences between the Python versions with the goal of

    writing Python code that is compatible on both Python versions.  See the

    documentation for more information on what is provided.


    Six supports every Python version since 2.6.  It is contained in only one Python

    file, so it can be easily copied into your project. (The copyright and license

    notice must be retained.)


    Online documentation is at https://pythonhosted.org/six/.


    Bugs can be reported to https://github.com/benjaminp/six.  The code can also

    be found there.


    For questions about six or porting in general, email the python-porting mailing

    list: https://mail.python.org/mailman/listinfo/python-porting'
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
